---
collections:
  - awx.awx
  - ansible.posix
  - name: https://github.com/netcho/community.general
    version: fix-one-service-module
    type: git
  - community.crypto
  - ngine_io.cloudstack
  - netcho.opennebula
