- name: Starting Nginx
  become: yes
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes
  listen: Start Nginx

- name: Restarting Nginx
  become: yes
  ansible.builtin.systemd:
    name: nginx
    state: restarted
  listen: Restart Nginx

- name: Creating YUM repository
  become: true
  command: createrepo /var/www/repo/cloudstack/
  listen: Create YUM repository
