---
- name: "Building CloudStack {{ cs_version }}"
  hosts: management
  become: true
  become_method: sudo
  tasks:
    - name: Adding MySQL community repo
      yum_repository:
        name: mysql-community
        description: MySQL Community connectors
        baseurl: http://repo.mysql.com/yum/mysql-connectors-community/el/$releasever/$basearch/
        enabled: true
        gpgkey: http://repo.mysql.com/RPM-GPG-KEY-mysql
        gpgcheck: true

    - name: Installing CloudStack build dependencies
      yum:
        name:
          - bzip2
          - "@Development Tools"
          - maven
          - genisoimage
          - mariadb
          - ws-commons-util
          - MySQL-python
          - mysql-connector-python

    - name: "Downloading CloudStack {{ cs_version }} source code archive"
      get_url:
        url: "https://archive.apache.org/dist/cloudstack/releases/{{ cs_version }}/apache-cloudstack-{{ cs_version }}-src.tar.bz2"
        dest: /home/centos/

    - name: Extracting source code archive
      unarchive:
        src: "/home/centos/apache-cloudstack-{{ cs_version }}-src.tar.bz2"
        remote_src: true
        dest: /home/centos/

    - name: Creating RPMs to distribute and install
      command:
        argv:
          - /bin/bash
          - "/home/centos/apache-cloudstack-{{ cs_version }}-src/packaging/package.sh"
          - -d centos7
