---
- name: "Building CloudStack {{ cs_version }}"
  hosts: management
  tasks:
    - name: Adding MySQL community repo
      become: true
      become_method: sudo
      yum_repository:
        name: mysql-community
        description: MySQL Community connectors
        baseurl: http://repo.mysql.com/yum/mysql-connectors-community/el/$releasever/$basearch/
        enabled: true
        gpgkey: http://repo.mysql.com/RPM-GPG-KEY-mysql
        gpgcheck: true

    - name: Installing CloudStack build dependencies
      become: true
      become_method: sudo
      yum:
        name:
          - "@Development Tools"
          - maven
          - genisoimage
          - mariadb
          - ws-commons-util
          - MySQL-python
          - mysql-connector-python

    - name: Cloning CloudStack GitHub repository
      git:
        repo: https://github.com/apache/cloudstack.git
        dest: /home/centos/cloudstack-src
        version: "{{ cs_version }}"

    - name: Creating RPMs to distribute and install
      shell: "/bin/bash ./package.sh -d centos7"
      args:
        chdir: "/home/centos/cloudstack-src/packaging/"

