---
- name: Installing StorPool
  hosts: storpool_nodes
  become_method: sudo
  pre_tasks:
    - name: Setting corresponding CloudStack cluster name
      set_fact:
        cloudstack_cluster: "{{ 'cluster_' + user_attributes.cloudstack_cluster }}"
  roles:
    - generate-storpool-config
    - add-storpool-repo
    - install-sp-python
    - install-storpool-services
    - configure-networking

- name: Initializing StorPool disks
  hosts: storpool_server_nodes
  become_method: sudo
  roles:
    - initialize-drives

- name: Configuring control groups
  hosts: storpool_nodes
  become_method: sudo
  roles:
    - configure-cgroups
  post_tasks:
    - import_tasks: tasks/configure_services.yaml

- name: Configuring remote bridges
  hosts: storpool_server_nodes
  tasks:
    - import_tasks: tasks/configure_bridges.yaml

- name: Configuring storage template
  hosts: storpool_server_nodes
  tasks:
    - import_tasks: tasks/configure_template.yaml
