---
- name: Provision infrastructure
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Generating unique name
      set_fact:
        deployment_name: "lab-cs-{{ lab_environment }}-{{ sp_version }}-{{ cs_version }}-{{ plugin_version }}"
    - name: Generating OpenSSH keypair
      openssh_keypair:
        path: "/tmp/{{ deployment_name }}-keypair"
    - name: Adding keypair as Machine credential to AWX
      tower_credential:
        name: "{{ deployment_name }}"
        credential_type: Machine
        inputs:
          username: centos
          ssh_key_data: "{{ lookup('file', '/tmp/' + deployment_name + '-keypair') }}"
          ssh_public_key_data: "{{ lookup('file', '/tmp/' + deployment_name + '-keypair.pub') }}"
          become_method: sudo
    - name: Instantiating OpenNebula service
      one_service:
        template_id: "{{ one_template_id }}"
        service_name: "{{ deployment_name }}"
        custom_attrs:
          ENVIRONMENT: "{{ lab_environment }}"
          STORPOOL_VERSION: "{{ sp_version }}"
          CLOUDSTACK_VERSION: "{{ cs_version }}"
          STORPOOL_PLUGIN_VERSION: "{{ plugin_version }}"
          ANSIBLE_PUBLIC_KEY: "{{ lookup('file', '/tmp/' + deployment_name + '-keypair.pub') }}"
        unique: true
        wait: true
    - name: Creating AWX inventory
      tower_inventory:
        name: "{{ deployment_name }}"
        organization: Default
    - name: Creating management inventory group
      block:
        - name: Retrieve management VMs from OpenNebula
          one_vm:
            attributes:
              ENVIRONMENT: "{{ lab_environment }}"
              STORPOOL_VERSION: "{{ sp_version }}"
              CLOUDSTACK_VERSION: "{{ cs_version }}"
              STORPOOL_PLUGIN_VERSION: "{{ plugin_version }}"
              ROLE_NAME: management
          register: management_hosts
        - name: Adding management VMs to inventory
          tower_host:
            inventory: "{{ deployment_name }}"
            name: "{{ item.vm_name }}"
            variables:
              ansible_host: "{{ item.networks[0].ip }}"
              ansible_user: centos
          loop: "{{ management_hosts.instances }}"
        - name: Adding management VMs to management group
          tower_group:
            inventory: "{{ deployment_name }}"
            name: management
            hosts: "{{ management_hosts.instances|map(attribute='vm_name') }}"
