---
- name: "Building CloudStack {{ cs_version }}"
  hosts: management
  roles:
    - build-cloudstack

- name: "Installing CloudStack repository"
  hosts: all
  roles:
    - add-cloudstack-repository

- name: "Installing CloudStack management node"
  hosts: management
  roles:
    - cloudstack-management
