---
- name: Generating StorPool configuration
  hosts: "{{ cluster_group }}"
  become: true
  become_method: sudo
  roles:
    - generate-storpool-config

- name: Installing StorPool converged node
  hosts: "{{ cluster_group }}_block_server_mgmt"
  become: true
  become_method: sudo
  roles:
    - install-storpool-services
    - initialize-drives
    - configure-cgroups
  vars:
    converged: true

- name: Installing StorPool client node
  hosts: "{{ cluster_group }}_block"
  become: true
  become_method: sudo
  roles:
    - install-storpool-services
    - configure-cgroups
  vars:
    converged: false

- name: Starting StorPool services
  hosts: "{{ cluster_group }}"
  become: true
  become_method: sudo
  tasks:
    - name: Starting StorPool services
      command: /usr/sbin/storpool_ctl start