---
- name: Generating StorPool configuration
  hosts: "{{ cluster_group }}"
  become: true
  become_method: sudo
  roles:
    - generate-storpool-config

- name: Installing StorPool hyperconverged node
  hosts: "{{ cluster_group }}_block_server_mgmt"
  become: true
  become_method: sudo
  roles:
    - install-storpool-block-server-mgmt

- name: Installing StorPool client node
  hosts: "{{ cluster_group }}_block_server_mgmt"
  become: true
  become_method: sudo
  roles:
    - install-storpool-block

- name: Starting StorPool services
  hosts: "{{ cluster_group }}"
  become: true
  become_method: sudo
  roles:
    - start-storpool-services