---
- name: Installing StorPool
  hosts: storpool_nodes
  become: true
  become_method: sudo
  pre_tasks:
    - name: Setting corresponding CloudStack cluster name
      set_fact:
        cloudstack_cluster: "{{ 'cluster_' + user_attributes.cloudstack_cluster }}"
  roles:
    - generate-storpool-config
    - add-storpool-repo
    - install-sp-python
    - install-storpool-services
    - configure-networking

- name: Initializing StorPool disks
  hosts: storpool_server_nodes
  become: true
  become_method: sudo
    - initialize-drives

- name: Configuring control groups
  hosts: storpool_nodes
  become: true
  become_method: sudo
  roles:
    - configure-cgroups
  post_tasks:
    - name: Enabling StorPool services
      command: /usr/sbin/storpool_ctl enable
    - name: Starting StorPool services
      command: /usr/sbin/storpool_ctl start