---
- name: Provision infrastructure
  hosts: localhost
  gather_facts: false
  vars:
    cloudstack_clusters: []
  tasks:
    - name: Generating unique name
      set_fact:
        deployment_name: "lab-cs-{{ lab_environment }}-{{ sp_version }}-{{ cs_version }}-{{ plugin_version }}"
    - name: Instantiating OpenNebula service
      one_service:
        template_id: "{{ one_template_id }}"
        service_name: "{{ deployment_name }}"
        custom_attrs:
          ENVIRONMENT: "{{ lab_environment }}"
          STORPOOL_VERSION: "{{ sp_version }}"
          CLOUDSTACK_VERSION: "{{ cs_version }}"
          STORPOOL_PLUGIN_VERSION: "{{ plugin_version }}"
        unique: true
        wait: true
