---
- name: Provision infrastructure
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/os_image_user_map.yaml
  tasks:
    - name: Generating unique name
      set_fact:
        deployment_name: "lab-cs-{{ lab_environment }}-{{ sp_version }}-{{ cs_version }}-{{ plugin_version }}"
    - name: Dumping image id and cloud user
      debug:
        msg: "Selected OS {{ os_image_user_list | selectattr('name', 'eq', os_name) | first }}"
        verbosity: 2
    - name: Instantiating OpenNebula service
      one_service:
        template_id: "{{ one_template_id }}"
        service_name: "{{ deployment_name }}"
        custom_attrs:
          ENVIRONMENT: "{{ lab_environment }}"
          STORPOOL_VERSION: "{{ sp_version }}"
          CLOUDSTACK_VERSION: "{{ cs_version }}"
          STORPOOL_PLUGIN_VERSION: "{{ plugin_version }}"
          VM_IMAGE_ID: "{{ (os_image_user_list | selectattr('name', 'eq', os_name) | first )['one_image_id'] }}"
          CLOUD_USER: "{{ (os_image_user_list | selectattr('name', 'eq', os_name) | first )['cloud_user'] }}"
        unique: true
        wait: true
