---
- name: Fetching mounted drives
  set_fact:
    mounted_drives: "{{ ansible_mounts | map(attribute='device') | map('regex_search', '[s|v][a-z]{2,}') }}"

- name: Retrieving available drives
  set_fact:
    available_drives: "{{ lookup('dict', ansible_devices) | map(attribute='key') | reject('in', mounted_drives) | map('regex_search', '[s|v][a-z]{2,}') | select('string') }}"

- name: Show list of available drives
  debug:
    msg: "Available drives to StorPool {{ available_drives }}"
    verbosity: 2

- name: Formating disks
  become: true
  parted:
    device: "/dev/{{ disk }}"
    number: 1
    state: present
    label: gpt
    part_start: 2MiB
  loop: "{{ available_drives }}"
  loop_control:
    loop_var: disk

- name: Retrieving SP_OURID value using storpool_showconf
  command: /usr/sbin/storpool_showconf -n SP_OURID
  register: storpool_showconf_sp_ourid

- name: Initializing disks
  become: true
  command: >-
    /usr/sbin/storpool_initdisk
    --no-notify
    {% if (diskId + 1) == 1 and ( inventory_hostname | split("-") | last ) == "0" %}
    -I
    {% endif %}
    {{ (storpool_showconf_sp_ourid.stdout | int) * 100 + diskId + 1 }}
    /dev/{{ disk }}1
  loop: "{{ available_drives }}"
  loop_control:
    loop_var: disk
    index_var: diskId