- name: Adding Hypervisors
  ngine_io.cloudstack.cs_host:
    name: "{{ hypervisor_name }}"
    username: cloudstack
    password: "{{ cloudstack_user_password }}"
    zone: "Zone-{{ cluster_name[0] | upper }}"
    pod: "Pod-{{ cluster_name[0] | upper }}"
    cluster: "Cluster-{{ cluster_name | upper }}"
    api_url: "http://{{ ansible_host }}:8080/client/api"
    api_key: "{{ cs_api_key }}"
    api_secret: "{{ cs_secret_key }}"
  loop_control:
    loop_var: hypervisor_name
  loop: "{{ groups['cloudstack_hypervisors'] }}"
  var:
    cluster_name: "{{ hostvars[hypervisor_name].user_attributes.cloudstack_cluster }}"
