---
- name: Generating lab_environment_id
  set_fact:
    lab_environment_id: "lab-cs-{{ lab_environment }}-{{ sp_version }}-{{ cs_version }}-{{ plugin_version }} | to_uuid"

- name: Generating a list of hosts that are part of the environment
  set_fact:
    environment_hosts: "{{ hostvars | dict2items(key_name='name', value_name='vars') | selectattr('vars.user_attributes.lab_environment_id', 'eq', lab_environment_id) | list }}"

- name: Generating cloudstack_management group
  add_host:
    hostname: "{{ host.name }}"
    groups:
      - cloudstack_management
      - environment_hosts
  loop: "environment_hosts | selectattr('vars.user_attributes.role_name', 'eq', 'management') | list }}"
  loop_control:
    loop_var: host

- name: Printing cloudstack_management group
  debug:
    var: "{{ groups['cloudstack_management'] }}"
    verbosity: 2

- name: Generating storpool_nodes group
  add_host:
    hostname: "{{ host.name }}"
    groups:
      - storpool_nodes
      - environment_hosts
  loop: "{{ environment_hosts | selectattr('vars.user_attributes.role_name', 'ne', 'management') | list }}"
  loop_control:
    loop_var: host

- name: Printing storpool_nodes group
  debug:
    var: "{{ groups['storpool_nodes'] }}"
    verbosity: 2

- name: Generating storpool_server_nodes group
  add_host:
    hostname: "{{ host.name }}"
    groups:
      - storpool_server_nodes
  loop: "{{ environment_hosts | selectattr('vars.user_attributes.role_name', 'ne', 'management') | selectattr('vars.user_attributes.storpool_services', 'contains', 'server') | list }}"
  loop_control:
    loop_var: host

- name: Printing storpool_server_nodes group
  debug:
    var: "{{ groups['storpool_server_nodes'] }}"
    verbosity: 2
