---
- name: Adding entry in /etc/hosts to management node
  become: true
  lineinfile:
    path: /etc/hosts
    line: "{{ cs_management_ip }} cloudstack.repo"

- name: Adding yum repository
  become: true
  yum_repository:
    file: cloudstack.repo
    name: apache-cloudstack
    description: Locally built Apache CloudStack
    baseurl: http://cloudstack.repo/
    enabled: true
    gpgcheck: false