---
- name: Getting cloudstack management hostname
  set_fact:
    cloudstack_management_hostname: "{{ groups['cloudstack_management'] | first }}"

- name: Adding entry in /etc/hosts to management node
  become: true
  lineinfile:
    path: /etc/hosts
    line: "{{ (hostvars[cloudstack_management_hostname].nic | first).ip }} cloudstack.repo"

- name: Adding yum repository
  become: true
  yum_repository:
    file: cloudstack.repo
    name: apache-cloudstack
    description: Locally built Apache CloudStack
    baseurl: http://cloudstack.repo/
    enabled: true
    gpgcheck: false