---
systemvm_template_base_url: https://download.cloudstack.org/systemvm
systemvm_template_version_overrides:
  4.13.1.0: 4.11.3
  4.16.0.0: 4.16.0
  4.16.1.0: 4.16.1
  4.17.0.0: 4.17.0
  4.17.1.0: 4.17.0

nfs_export_directories:
  - /export/primary
  - /export/secondary

cloudmonkey_version: 6.1.0

admin_user_id_json_query: user[?username=='admin'].id | [0]
user_has_keys_json_query: (userkeys | keys(@) | contains(@, 'apikey')) "&&" (userkeys | keys(@) | contains(@, 'secretkey'))
