---
systemvm_template_base_url: https://download.cloudstack.org/systemvm
systemvm_template_version_overrides:
  4.13.1.0: 4.11.3

nfs_export_directories:
  - /export/primary
  - /export/secondary

cloudmonkey_version: 6.1.0

admin_user_id_json_query: "user[?username=='admin'].id | [0]"
user_has_keys_json_query: "(userkeys | keys(@) | contains(@, 'apikey') and (userkeys | keys(@) | contains(@, 'secretkey')"
