- name: Adding zones
  ngine_io.cloudstack.cs_zone:
    name: "{{ zone.name }}"
    dns1: "{{ zone.dns_server }}"
    guest_cidr_address: "{{ zone.clients_prefix }}"
    api_url: http://localhost:8080/client/api
    api_key: "{{ cs_api_key }}"
    api_secret: "{{ cs_secret_key }}"
  loop: "{{ sp_cluster_params[lab_environment]['cloudstack_zones'] }}"
  loop_control:
    loop_var: zone

- name: Adding pods
  ngine_io.cloudstack.cs_pod:
    name: "{{ pod.name }}"
    start_ip: "{{ pod.start_ip }}"
    netmask: "{{ pod.network_prefix }}"
    gateway: "{{ pod.gateway }}"
    api_url: http://localhost:8080/client/api
    api_key: "{{ cs_api_key }}"
    api_secret: "{{ cs_secret_key }}"
  loop: "{{ sp_cluster_params[lab_environment]['cloudstack_pods'] }}"
  loop_control:
    loop_var: pod
