- name: Adding CloudStack Zones
  ngine_io.cloudstack.cs_zone:
    name: "{{ zone.name }}"
    dns1: "{{ zone.dns_server }}"
    securitygroups_enabled: yes
    api_url: "http://{{ ansible_host }}:8080/client/api"
    api_key: "{{ cs_api_key }}"
    api_secret: "{{ cs_secret_key }}"
  loop: "{{ sp_cluster_params[lab_environment]['cloudstack_zones'] }}"
  loop_control:
    loop_var: zone

- name: Adding CloudStack Pods
  ngine_io.cloudstack.cs_pod:
    name: "{{ pod.name }}"
    zone: "{{ pod.zone }}"
    start_ip: "{{ pod.start_ip }}"
    netmask: "{{ pod.network_mask }}"
    gateway: "{{ pod.gateway }}"
    api_url: "http://{{ ansible_host }}:8080/client/api"
    api_key: "{{ cs_api_key }}"
    api_secret: "{{ cs_secret_key }}"
  loop: "{{ sp_cluster_params[lab_environment]['cloudstack_pods'] }}"
  loop_control:
    loop_var: pod

- name: Adding CloudStack clusters
  ngine_io.cloudstack.cs_cluster:
    name: "Cluster-{{ cluster_name }}"
    zone: "{{ cluster_info.zone }}"
    pod: "{{ cluster_info.pod }}"
    cluster_type: CloudManaged
    hypervisor: KVM
    username: "{{ cloudstack_hypervisor_username }}"
    api_url: "http://{{ ansible_host }}:8080/client/api"
    api_key: "{{ cs_api_key }}"
    api_secret: "{{ cs_secret_key }}"
  loop: "{{ sp_cluster_params[lab_environment] | dict2items | selectattr('key', 'contains', 'cluster') | list }}"
  loop_control:
    loop_var: cluster_tuple
  vars:
    cluster_name: "{{ cluster_tuple.key | split ('_') | last | upper }}"
    cluster_info: "{{ cluster_tuple.value }}"
