- name: Adding CloudStack Zones
  ngine_io.cloudstack.cs_zone:
    name: "{{ zone.name }}"
    dns1: "{{ zone.dns_server }}"
    securitygroups_enabled: yes
    api_url: "http://{{ ansible_host }}:8080/client/api"
    api_key: "{{ cs_api_key }}"
    api_secret: "{{ cs_secret_key }}"
  loop: "{{ sp_cluster_params[lab_environment]['cloudstack_zones'] }}"
  loop_control:
    loop_var: zone

- name: Adding CloudStack Pods
  ngine_io.cloudstack.cs_pod:
    name: "{{ pod.name }}"
    zone: "{{ pod.zone }}"
    start_ip: "{{ pod.start_ip }}"
    netmask: "{{ pod.network_mask }}"
    gateway: "{{ pod.gateway }}"
    api_url: "http://{{ ansible_host }}:8080/client/api"
    api_key: "{{ cs_api_key }}"
    api_secret: "{{ cs_secret_key }}"
  loop: "{{ sp_cluster_params[lab_environment]['cloudstack_pods'] }}"
  loop_control:
    loop_var: pod
