---
- name: Installing cloudstack-management
  become: true
  package:
    name:
      - cloudstack-management
      - mysql-server
    state: latest

- name: Creating MariaDB drop-in config for CloudStack
  become: true
  copy:
    src: cloudstack.cnf
    dest: /etc/my.cnf.d/
    mode: 0644
  notify: Restart MySQL server

- name: Starting MySQL server
  become: true
  systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Checking if CloudStack database password is defined
  assert:
    that:
      - cloudstack_db_password is defined
      - cloudstack_db_password | length
    fail_msg: Please define a database password to be used by CloudStack database user

- name: Initializing CloudStack database
  become: true
  command:
    argv:
      - /usr/bin/cloudstack-setup-databases
      - "cloud:{{ cloudstack_db_password }}@localhost"
      - --deploy-as=root
    creates: /etc/cloudstack/management/.ansible_db_initialized
  notify: Setup CloudStack management

- name: Flushing handlers
  meta: flush_handlers
