---
- name: Installing cloudstack-management and mariadb packets
  become: true
  package:
    name:
      - cloudstack-management
      - mariadb-server
    state: latest

- name: Creating MariaDB drop-in config for CloudStack
  become: true
  copy:
    src: cloudstack.cnf
    dest: /etc/my.cnf.d/
    mode: 0644
  register: cloudstack_config

- name: Restarting MariaDB
  become: true
  systemd:
    name: mariadb
    state: restarted
  when: cloudstack_config.changed

- name: Initializing CloudStack database
  become: true
  command:
    argv:
      - /usr/bin/cloudstack-setup-databases
      - "cloud:{{ lookup('password', '/dev/null length=8 chars=ascii_lowercase,digits') }}@localhost"
      - --deploy-as=root

- name: Setting up CloudStack management
  become: true
  command: /usr/bin/cloudstack-setup-management
