---
- name: Installing cloudstack-management
  become: true
  package:
    name:
      - cloudstack-management
      - mysql-server
    state: latest

- name: Creating MariaDB drop-in config for CloudStack
  become: true
  copy:
    src: cloudstack.cnf
    dest: /etc/my.cnf.d/
    mode: 0644
  register: cloudstack_config

- name: Restarting MySQL server
  become: true
  systemd:
    name: mysqld
    state: restarted
    enabled: true
  when: cloudstack_config.changed

- name: Initializing CloudStack database
  become: true
  command:
    argv:
      - /usr/bin/cloudstack-setup-databases
      - "cloud:{{ lookup('password', '/dev/null length=8 chars=ascii_lowercase,digits') }}@localhost"
      - --deploy-as=root
    creates: /etc/cloudstack/management/db.properties

- name: Setting up CloudStack management
  become: true
  command: /usr/bin/cloudstack-setup-management
