---
- name: Running storpool-cg conf
  command: "/usr/sbin/storpool_cg conf CONVERGED={{'1' if converged else '0'}} SYSTEM_LIMIT=2 USER_LIMIT=1"

- name: Restarting cgconfig
  systemd:
    name: cgconfig
    enabled: true
    state: restarted
