---
- name: "Retrieving {{ service_role_name }} VMs from OpenNebula"
  one_vm:
    attributes:
      ENVIRONMENT: "{{ lab_environment }}"
      STORPOOL_VERSION: "{{ sp_version }}"
      CLOUDSTACK_VERSION: "{{ cs_version }}"
      STORPOOL_PLUGIN_VERSION: "{{ plugin_version }}"
      ROLE_NAME: "{{ service_role_name }}"
  register: hosts

- name: Adding StorPool VMs to inventory
  vars:
    base_hostname: "{{ 'lab-cs-' + lab_environment + '-' + (service_role_name | replace('_', '-')) }}"
    hosts: "{{ hosts }}"
  include_tasks: populate_storpool_nodes.yaml
  when: '"cluster" in service_role_name'

- name: Adding CloudStack management VMs to inventory
  vars:
    base_hostname: "{{ 'lab-cs-' + lab_environment + '-management' }}"
    hosts: "{{ hosts }}"
  include_tasks: populate_cloudstack_management.yaml
  when: '"management" in service_role_name'
