- name: Setting hostname
  become: true
  hostname:
    name: "{{ 'lab-cs-' + lab_environment + '-' + ('mgmt' if 'management' == user_attributes.role_name else user_attributes.cloudstack_cluster + '-' + storpool_services | join ('-'))}}"

- name: Adding StorPool support key from file
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ sp_support_key }}"

- name: Disabling firewalld on RedHat family
  systemd:
    name: firewalld
    state: stopped
    enabled: false
  when: ansible_os_familly == "RedHat"
