---
- name: Creating StorPool installation directory
  file:
    path: "{{ ansible_user_dir }}/storpool/"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0664

- name: Downloading StorPool installation tools
  get_url:
    url: "https://vault.storpool.com/{{ tool_name }}"
    dest: "{{ ansible_user_dir }}/storpool/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  loop:
    - getpackage.py
    - install_modules_helper.py
  loop_control:
    loop_var: tool_name

- name: Downloading StorPool
  command: "{{ ansible_user_dir }}/storpool/getpackage.py -g {{ sp_version }} -w {{ ansible_user_dir }}/storpool/ -t {{ sp_release_target }}"
  become: true
  args:
    creates: "{{ ansible_user_dir }}/storpool/storpool-{{ sp_version }}*.tar.gz"

- name: Installing StorPool services
  become: true
  command: "{{ ansible_user_dir }}/storpool/install_modules_helper.py -g {{ sp_version }} -m {{ '@' + ( storpool_services | join ('_') ) }} "
