---
- name: Adding MySQL community repo
  become: true
  become_method: sudo
  yum_repository:
    name: mysql-community
    description: MySQL Community connectors
    baseurl: http://repo.mysql.com/yum/mysql-connectors-community/el/$releasever/$basearch/
    enabled: true
    gpgkey: http://repo.mysql.com/RPM-GPG-KEY-mysql
    gpgcheck: true

- name: Installing CloudStack build dependencies
  become: true
  become_method: sudo
  yum:
    name:
      - bzip2
      - "@Development Tools"
      - maven
      - genisoimage
      - mariadb
      - ws-commons-util
      - MySQL-python
      - mysql-connector-python
      - createrepo

- name: Cloning CloudStack GitHub repository
  git:
    repo: https://github.com/apache/cloudstack.git
    dest: /home/centos/cloudstack-src
    version: "{{ cs_version }}"
  when: git_checkout | bool

- name: Building RPMs
  shell: FLAGS=-DskipTests ./package.sh -d centos7
  args:
    chdir: /home/centos/cloudstack-src/packaging/
    executable: /bin/bash
  when: build_rpms | bool

- name: Installing nginx
  yum:
    name:
      - nginx
    state: present

- name: Creating nginx server config directory
  become: true
  become_method: sudo
  file:
    src: /etc/nginx/conf.d/
    state: directory

- name: Uploading nginx configuration
  become: true
  become_method: sudo
  copy:
    src: repo.conf
    dest: /etc/nginx/conf.d/cloudstack-repo.conf

- name: Copying RPMs to repository
  become: true
  become_method: sudo
  copy:
    src: /home/centos/cloudstack-src/dist/rpmbuild/RPMS/x86_64/
    remote_src: true
    dest: /var/www/repo/cloudstack/

- name: Creating an YUM repository
  become: true
  become_method: sudo
  command: createrepo /var/www/repo/cloudstack/

- name: Restarting nginx
  systemd:
    name: nginx
    state: restarted
    enabled: true