---
- name: Adding MySQL community yum repo
  become: true
  yum_repository:
    name: mysql-community
    description: MySQL Community connectors
    baseurl: http://repo.mysql.com/yum/mysql-connectors-community/el/$releasever/$basearch/
    gpgkey: http://repo.mysql.com/RPM-GPG-KEY-mysql
    enabled: true
    gpgcheck: true

- name: Adding oVirt 44 repository
  become: true
  dnf:
    name:
      - https://resources.ovirt.org/pub/yum-repo/ovirt-release44.rpm
    state: present
    disable_gpg_check: true
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "8"

- name: Installing CloudStack build dependencies
  become: true
  yum:
    name:
      - bzip2
      - "@Development Tools"
      - maven
      - genisoimage
      - ws-commons-util
      - createrepo
      - mysql-connector-python
      - wget
      - java-11-openjdk
      - java-11-openjdk-devel
      - nodejs
    state: present

- name: Configuring java alternative
  become: true
  alternatives:
    name: java
    path: /usr/lib/jvm/java-11-openjdk/bin/java
    link: /usr/bin/java

- name: Configuring javac alternative
  become: true
  alternatives:
    name: javac
    path: /usr/lib/jvm/java-11-openjdk/bin/javac
    link: /usr/bin/javac

- name: Cloning CloudStack GitHub repository
  git:
    repo: https://github.com/storpool/cloudstack.git
    dest: "{{ ansible_user_dir }}/cloudstack-src"
    version: "{{ cs_version }}"
    depth: 1
  when: cloudstack_git_checkout | bool
  register: clone_result

- name: Building RPMs
  shell: |
    export JAVA_HOME=/usr/lib/jvm/java-11-openjdk
    FLAGS="-DskipTests -T 2C" ./package.sh -d centos{{ ansible_distribution_major_version }} | tee /tmp/cloudstack-build.log
  args:
    chdir: "{{ ansible_user_dir }}/cloudstack-src/packaging/"
    executable: /bin/bash
  register: build_packages_task
  when: clone_result.before == "null" or clone_result.after != clone_result.before

- name: Check if building the packages succeeded
  ansible.builtin.assert:
    that:
      - build_packages_task.rc == 0
    fail_msg: Building CloudStack binary packages failed

- name: Installing nginx
  become: true
  package:
    name: nginx
    state: present
  notify: Start Nginx

- name: Setting SELinux to permissive
  become: true
  selinux:
    state: permissive
    policy: targeted

- name: Creating nginx server config directory
  become: true
  file:
    path: /etc/nginx/conf.d/
    state: directory

- name: Uploading nginx configuration
  become: true
  copy:
    src: repo.conf
    dest: /etc/nginx/conf.d/cloudstack-repo.conf
  notify: Restart Nginx

- name: Copying RPMs to repository
  become: true
  copy:
    src: "{{ ansible_user_dir }}/cloudstack-src/dist/rpmbuild/RPMS/x86_64/"
    remote_src: true
    dest: /var/www/repo/cloudstack/
  notify: Create YUM repository
