---
- name: Installing CloudStack build dependencies
  become: true
  yum:
    name:
      - bzip2
      - "@Development Tools"
      - maven
      - genisoimage
      - ws-commons-util
      - createrepo
      - mysql-connector-python
    state: present

- name: Cloning CloudStack GitHub repository
  git:
    repo: https://github.com/apache/cloudstack.git
    dest: /home/centos/cloudstack-src
    version: "{{ cs_version }}"
  when: cloudstack_git_checkout | bool
  register: clone_result

- name: Building RPMs
  shell: "FLAGS=-DskipTests ./package.sh -d centos{{ ansible_distribution_major_version }}"
  args:
    chdir: /home/centos/cloudstack-src/packaging/
    executable: /bin/bash
  when: clone_result.before == "null" or clone_result.after != clone_result.before

- name: Installing nginx
  become: true
  package:
    name: nginx
    state: present

- name: Creating nginx server config directory
  become: true
  file:
    path: /etc/nginx/conf.d/
    state: directory

- name: Uploading nginx configuration
  become: true
  copy:
    src: repo.conf
    dest: /etc/nginx/conf.d/cloudstack-repo.conf
  register: nginx_repo_config

- name: Copying RPMs to repository
  become: true
  copy:
    src: /home/centos/cloudstack-src/dist/rpmbuild/RPMS/x86_64/
    remote_src: true
    dest: /var/www/repo/cloudstack/
  register: copy_rpms

- name: Creating an YUM repository
  become: true
  command: createrepo /var/www/repo/cloudstack/
  when: copy_rpms.changed

- name: Restarting nginx
  become: true
  systemd:
    name: nginx
    state: restarted
    enabled: true
  when: nginx_repo_config.changed

- name: Setting SELinux to permissive
  become: true
  selinux:
    state: permissive
    policy: targeted